language: php
php:
  - "5.6"
cache:
  directories:
  - vendor
addons:
  sauce_connect: true
before_script:
  - composer install -o
script:
- vendor/bin/behat -p live-sauce
env:
  # SAUCELABS
  - secure: kaqIGFh/36ECQw1Ss+gT6z58a8cDux65cAE3pZi3dq09UDp756FFTDjbsQ3MD8ypk3+1osvlfDaXTTJiEGnfn0Db7wst2sJAQrf9nWEc/HMknmlHv8TrdQB0ldBhU7UrLlr0MvOqJX0Iwo5t+8J+j2dZT6Ffctz6HPh5cbCzZUhXojtUEjzrMGN16bVjtFMDmzTk8zzljPK1N7ogFF4OwrLWTYOvDinj5pWQsJ2TGdzL4k9jWtaIS2TqiT5RTiUuGOd2UDtuOOZW9JZdH8Zl+TneODeInJTjBJKwO+KGkideHVh2zSenb/SjChWc645x10/iJSssPZBYvvLu5ioo3vx97BOXt31mV57aQTzxJmkhY1IV6GXQjH5sFaL/OoLwXz9gLTDcgF1w/9lFhSV8VUwEN/YBskgil6DghmP7awE0DQX+9hpC7gVCIlLhb3Mvkcw300cEx8KeP/IjjlAbCZWN79Tkq1kVAaDLuNiLx900obkc9oufaY3aHxpeaVtQERfchw0LZtSahxUulyZklsxxoU4Pw25oC/0ZiiTQIW/R3O5Tdich2SBShUumpeVMFXcPkmULb59NHUvgKS+D/ax9H0dOOWH3oCfvviqKDYlbe4PySn0afMflC5+tD59igzLIE98/nHW+6REcM5DXZNh48muulML6yYHvj31wgc8=
  - secure: VxC/1sAZd45wuFPg3mbz/ihFL9uMQA1/hISZrtg/sTyB/0SYoshhC1BXsQBhX7G2ASF5ETtVCRKBDaDU3oAwtzRKcbAqYVQ8PfOkFSX5t6UWC84lvgFedhFj+NWj0RZY44ILf8Y9JIKzkgZSz60f4RvJy2n1QtI52r3O06wJSagNhB3Zk7CQejIj+1FOr7KaLOmr72u7U15Ns4fTBf675AotmvE2rsxk3zIfiC1cpMyvlP+2wFnOA3MT9gc14Hcgwu4XNV+UuQEFooeMAqiNVXuiAL8V447PEt5o3mxFeMinCwmt8enoIV0oux/skcMB/a15CCbLuY3ThwJMDmqcUd0+URm2wAfAQGFkwDGbGNPLWutaKs4YoV2z9OhMTf42rqq71hqnZUCKSP4/GmNN+oNYZENd7LxLyCwgmgwabcpfUrGaGcn++q8E2yquV6bIkdoV9EsNuHjR4SC759mlCcytJvnBZstNgsE49GrUOCs6JMqu9rqNU0oiaE9ofAP0CRkdwZiCGcUoRuRz2NUIHtvtcr6xSAElTVHiW4hFT2tJwqb01y5UsQsqxuxFByUDQxi5r4RQYFgV35ki+XIdyzcLDLLjCe0nTxOtdIOLMjOjCRmglApKABDJ2Qz1gLMQj2x7vpz67eJSjCuQKfvMcYA6ulZtAydES7/J+BByA1A=
